-- =============================================
--  LUA: language-specific autocmds
--  None yet; add following the commented template when needed.
-- =============================================
-- vim.api.nvim_create_autocmd("BufWritePost", {
--   pattern = { "*.lua" },
--   callback = function()
--     -- e.g. auto-reload something after save
--   end,
-- })
