-- =============================================
--  LUA: language-specific keymaps
--  None yet; add here following the template when needed.
-- =============================================
-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = { "lua" },
--   callback = function()
--     vim.keymap.set("n", "<leader>R", "<cmd>source %<cr>",
--       { buffer = true, desc = "Lua: Run current file" })
--   end,
-- })
